language: erlang
sudo: false

otp_release:
  - 20.1

before_install:
  - git clone https://github.com/elixir-lang/elixir
  - cd elixir && make compile && cd ..

before_script:
  - export PATH=`pwd`/elixir/bin:$PATH
  - mix local.hex --force && mix local.rebar --force
  - mix deps.get

script:
  - mix format --check-formatted
  - mix test
